version: '3'
services:
    app:
        build:
            dockerfile: ./Dockerfile
            context: .
            target: development
        env_file: ./.env
        volumes:
            - .:/app
            - ./scripts:/usr/local/bin
        ports:
            - 8000:8000
        environment:
            PORT: "8000"
            TZ: "Asia/Tokyo"
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --general_log --general_log_file=/var/log/mysql/mysqld.log
        ports:
            - 3306:3306
        environment: 
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "gin_ent_sample"
            MYSQL_USER: "user"
            MYSQL_PASSWORD: "password"
            TZ: "UTC"
        volumes:
            - mysql:/var/lib/mysql
            - ./log/mysql:/var/log/mysql
volumes:
    mysql:
        driver: local
